Dev/main
mi4r/gophermart pull request #16
Opened 2024-09-30 12:59 UTC by rombintu

2024-10-01 17:36 UTC, tmvrus requested changes

2024-10-01 17:36 UTC, tmvrus commented on internal/server/accrual/handlers_tests.go
это тест без теста

2024-10-01 17:36 UTC, tmvrus commented on internal/server/accrual/accrual_system.go
> +	// gApi.GET("/orders/:number", s.ordersGetHandler)
где реализация вот этого хендлера?

2024-10-01 20:04 UTC, rombintu commented on cmd/gophermart/main.go
> +	done := make(chan struct{})
close(done) - закрывает же, после получения сигнала заверешния. Или это так не работает?

2024-10-01 20:10 UTC, rombintu commented on internal/server/accrual/accrual_system.go
> +	// gApi.GET("/orders/:number", s.ordersGetHandler)
в процессе)

2024-10-02 10:08 UTC, tmvrus commented on cmd/gophermart/main.go
> +	done := make(chan struct{})
у тебя там ниже канал для сигналов ОС, а этот просто создается а затем закрывается, больше ничего с ним не происходит. Не очень понимаю чего ты хотел этим добиться, но выглядит бесмысленно.

2024-10-05 11:59 UTC, tmvrus requested changes
миграции в трех разных местах, странно
![Uploading image.png…]()

2024-10-05 11:59 UTC, tmvrus commented on internal/config/default.go
> +	migrDirNameAccrual    string = "accrual"
https://github.com/mi4r/gophermart/pull/16/files#r1783094073

2024-10-05 11:59 UTC, tmvrus commented on internal/server/gophermart/handlers.go
> +	orderAccepted      string = "order number accepted for processing"
https://github.com/mi4r/gophermart/pull/16/files#r1783094073

2024-10-05 11:59 UTC, tmvrus commented on internal/storage/storage.go
> +	UserOrdersReadByLogin(login string) ([]storagemart.Order, error)
ф-и  хранения не поддерживают передачу контекста входящего запроса, материал 3го спринта

2024-10-05 11:59 UTC, tmvrus commented on internal/storage/storage.go
> +func NewStorageGophermart(driverType string, path string) StorageGophermart {
когда типы у аргументов одинаковые, можно писать короче
`driverType, path string`

2024-10-05 11:59 UTC, tmvrus commented on internal/server/gophermart/handlers.go
> +		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
это точно такой же пример протекающей абстрации о которой я писал в первом ревью

2024-10-05 11:59 UTC, tmvrus commented on internal/server/gophermart/handlers.go
> +	if err == pgx.ErrNoRows {
для безопасного и надежного сравнения ошибок рекомендуется использовать erros.Is это материал 3го спринта

2024-10-05 11:59 UTC, tmvrus commented on internal/server/gophermart/handlers.go
> +	if err == pgx.ErrNoRows {
+ тут все еще дырявая абстракция: зачем хендлеру знать какая база данных используется?

2024-10-05 11:59 UTC, tmvrus commented on internal/server/gophermart/handlers.go
> +	if err != nil && err != pgx.ErrNoRows {
errors.Is

2024-10-05 11:59 UTC, tmvrus commented on internal/server/middlewares.go
> +	GzipHeader = "gzip"
этой константе не обязательно быть экспортируемой, она используется только внутри пакета

2024-10-05 11:59 UTC, tmvrus commented on internal/storage/default/migrations/000001_init_all_in_one.up.sql
> +    status VARCHAR(50) DEFAULT 'NEW' NOT NULL CHECK (status IN ('NEW', 'REGISTERED', 'PROCESSING', 'INVALID', 'PROCESSED')),
если нужно жестко ограничить возможные значение со стороны базы, проще использовать ENUM

2024-10-05 11:59 UTC, tmvrus commented on internal/storage/drivers/pgx_driver.go
> +func (d *pgxDriver) UserReadAll() ([]storagemart.User, error) {
Для каких целей нужен этот метод?

2024-10-05 11:59 UTC, tmvrus commented on internal/storage/drivers/pgx_driver.go
> +	return orders, errors.Join(errs...)
вот это довольно странная практика, допустим будет 10 записей в базе, 5 нормально отсканируются и будет положены в orders, 5 с ошибкой, в результате будет 5 записей и 5 ошибок, что с этим делать вызывающему коду? На данный момент он никак не учитывает наличие данных в результате, если была ошибка, в таком случае зачем они там?

2024-10-09 10:55 UTC, tmvrus requested changes
не все замечания устранены

2024-10-09 10:55 UTC, tmvrus commented on internal/server/accrual/handlers.go
> +}
это когда?

2024-10-09 10:55 UTC, tmvrus commented on internal/storage/storage.go
> +	OrderRegUpdateStatus(status storagedefault.OrderStatus, number string) error
контекст не пробрасывается из входящего запроса

2024-10-10 15:05 UTC, rombintu commented on internal/server/accrual/handlers.go
> +}
не до конца понятно что это вообще должно быть, в ТЗ просто указано что существует такой ответ, но где его вставить, вопрос

2024-10-10 15:06 UTC, rombintu commented on internal/server/accrual/handlers.go
> +}
нужно какой то счетчик вести запросов? и при достижении отдавать этот ответ

2024-10-11 10:57 UTC, tmvrus commented on internal/server/accrual/handlers.go
> +}
просто сделай рандом для начала, 
этот ответ должен зависеть от "состояния" сервиса, грубо говоря, на сколько текущая нагрузка приближается к максимальной, но считать это в рамках выпускной работы бессмысленно, так что пусть будет рандом.

2024-10-15 11:24 UTC, tmvrus approved these changes

2024-10-15 11:24 UTC, tmvrus approved these changes

2024-10-15 11:33 UTC, merged